/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jarlen_gpuimagelibrary_YUVCoderLibrary */

#ifndef _Included_cn_jarlen_gpuimagelibrary_YUVCoderLibrary
#define _Included_cn_jarlen_gpuimagelibrary_YUVCoderLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jarlen_gpuimagelibrary_YUVCoderLibrary
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jarlen_gpuimagelibrary_YUVCoderLibrary_testJni
  (JNIEnv *, jclass);

/*
 * Class:     cn_jarlen_gpuimagelibrary_YUVCoderLibrary
 * Method:    YUVtoRBGA
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_cn_jarlen_gpuimagelibrary_YUVCoderLibrary_YUVtoRBGA
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     cn_jarlen_gpuimagelibrary_YUVCoderLibrary
 * Method:    YUVtoARBG
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_cn_jarlen_gpuimagelibrary_YUVCoderLibrary_YUVtoARBG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
